ALTER TABLE "Domains" ADD COLUMN "IsArchived" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Domains" ADD COLUMN "ArchivedAt" TIMESTAMP NULL;

ALTER TABLE "KnowledgeNodes" ADD COLUMN "IsArchived" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "KnowledgeNodes" ADD COLUMN "ArchivedAt" TIMESTAMP NULL;
