CREATE TABLE LogEntryTags (
    LogId INT NOT NULL,
    TagId INT NOT NULL,
    PRIMARY KEY (LogId, TagId),
    FOREIGN KEY (LogId) REFERENCES LogEntries(LogId) ON DELETE CASCADE,
    FOREIGN KEY (TagId) REFERENCES Tags(TagId) ON DELETE CASCADE
);