-- PostgreSQL schema for KnowledgeCenterDB
-- Reverse-engineered from the live SQL Server instance (MORTENSENS-MPC\SQLEXPRESS)
-- on 2026-09-06. No stored procedures, triggers, or T-SQL-specific logic exist in
-- this database, so this file is the complete conversion for the schema step.
--
-- IMPORTANT: every identifier is double-quoted to preserve exact PascalCase casing.
-- DataAccess/Database.cs builds result rows as Dictionary<string, object> keyed by
-- reader.GetName(i), and the service layer looks columns up by exact name
-- (e.g. row["DomainName"], row["DomainId"]). Unquoted Postgres identifiers fold to
-- lowercase, which would silently break every one of those lookups at runtime.
-- Any hand-written SQL ported from the *Queries.cs classes must also quote
-- identifiers (e.g. "DomainName", not DomainName) so returned column names match.
--
-- IDENTITY columns use GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so a data-copy
-- step can insert explicit IDs carried over from SQL Server. After copying data,
-- reset each sequence, e.g.:
--   SELECT setval(pg_get_serial_sequence('"Domains"', 'DomainId'), (SELECT MAX("DomainId") FROM "Domains"));

CREATE TABLE "Domains" (
    "DomainId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DomainName" VARCHAR(100),
    "DomainStatus" VARCHAR(50),
    "DomainDescription" TEXT,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(),
    "LastUsed" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "KnowledgeNodes" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(255) NOT NULL,
    "Description" TEXT,
    "ConfidenceLevel" INTEGER,
    "Status" VARCHAR(50),
    "CreatedAt" TIMESTAMP NOT NULL,
    "LastUpdated" TIMESTAMP NOT NULL,
    "NodeType" VARCHAR(50) NOT NULL DEFAULT 'Concept',
    -- NOTE: SQL Server default is 0, but no Domains row with DomainId = 0 is guaranteed
    -- to exist. This FK will reject that default on insert unless the app always
    -- supplies a real DomainId (same constraint SQL Server enforces today) or a
    -- Domains row with DomainId 0 is seeded. Carried over as-is; not a Postgres-specific issue.
    "DomainId" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "FK_KnowledgeNodes_Domains" FOREIGN KEY ("DomainId") REFERENCES "Domains" ("DomainId")
);

CREATE TABLE "LogEntries" (
    "LogId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NodeId" INTEGER NOT NULL,
    "EntryDate" TIMESTAMP NOT NULL,
    "Title" VARCHAR(200),
    "Content" TEXT,
    "ContributesToProgress" BOOLEAN NOT NULL,
    "ChatURL" VARCHAR(2000),
    CONSTRAINT "FK_LogEntries_KnowledgeNodes" FOREIGN KEY ("NodeId") REFERENCES "KnowledgeNodes" ("Id")
);

CREATE TABLE "Tags" (
    "TagId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "Users" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" VARCHAR(50) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "LogEntryTags" (
    "LogId" INTEGER NOT NULL,
    "TagId" INTEGER NOT NULL,
    PRIMARY KEY ("LogId", "TagId"),
    CONSTRAINT "FK_LogEntryTags_LogEntries" FOREIGN KEY ("LogId") REFERENCES "LogEntries" ("LogId") ON DELETE CASCADE,
    CONSTRAINT "FK_LogEntryTags_Tags" FOREIGN KEY ("TagId") REFERENCES "Tags" ("TagId") ON DELETE CASCADE
);
